name: Daily AI News Email

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Create message
        run: |
          echo "🚀 Daily AI Updates:

          - AI impacting jobs globally
          - Rise of agentic AI
          - AI adoption in healthcare growing
          - Companies restructuring with AI

          Stay ahead 🔥" > message.txt

      - name: Send via Gmail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.APP_PASSWORD }}
          subject: Daily AI Updates
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
          body: file://message.txt
